name = "quiz-saas"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# Worker principal gerado pelo next-on-pages
main = ".vercel/output/static/_worker.js/index.js"

# Assets estáticos servidos pelo Worker
[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
