// lib/design/paletas.js
// 12 paletas prontas — estilo Canva

export const paletas = [
  {
    id: 'clean-preto',
    nome: 'Clean Preto',
    preview: ['#FFFFFF', '#111827', '#E5E7EB'],
    fundo: '#FFFFFF',
    fundoSecundario: '#F9FAFB',
    texto: '#111827',
    textoSuave: '#6B7280',
    textoRodape: '#9CA3AF',
    destaque: '#111827',
    destaqueSuave: '#F3F4F6',
    cardFundo: '#FFFFFF',
    cardBorda: '#E5E7EB',
    cardBordaSelecionada: '#111827'
  },
  {
    id: 'azul-confianca',
    nome: 'Azul Confiança',
    preview: ['#FFFFFF', '#0EA5E9', '#E0F2FE'],
    fundo: '#FFFFFF',
    fundoSecundario: '#F0F9FF',
    texto: '#0F172A',
    textoSuave: '#64748B',
    textoRodape: '#94A3B8',
    destaque: '#0EA5E9',
    destaqueSuave: '#E0F2FE',
    cardFundo: '#FFFFFF',
    cardBorda: '#E2E8F0',
    cardBordaSelecionada: '#0EA5E9'
  },
  {
    id: 'verde-saude',
    nome: 'Verde Saúde',
    preview: ['#FFFFFF', '#10B981', '#D1FAE5'],
    fundo: '#FFFFFF',
    fundoSecundario: '#F0FDF4',
    texto: '#064E3B',
    textoSuave: '#6B7280',
    textoRodape: '#9CA3AF',
    destaque: '#10B981',
    destaqueSuave: '#D1FAE5',
    cardFundo: '#FFFFFF',
    cardBorda: '#D1FAE5',
    cardBordaSelecionada: '#10B981'
  },
  {
    id: 'rosa-feminino',
    nome: 'Rosa Feminino',
    preview: ['#FFF1F2', '#EC4899', '#FCE7F3'],
    fundo: '#FFF1F2',
    fundoSecundario: '#FFE4E6',
    texto: '#831843',
    textoSuave: '#9F1239',
    textoRodape: '#BE185D',
    destaque: '#EC4899',
    destaqueSuave: '#FCE7F3',
    cardFundo: '#FFFFFF',
    cardBorda: '#FBCFE8',
    cardBordaSelecionada: '#EC4899'
  },
  {
    id: 'roxo-premium',
    nome: 'Roxo Premium',
    preview: ['#FFFFFF', '#8B5CF6', '#EDE9FE'],
    fundo: '#FFFFFF',
    fundoSecundario: '#F5F3FF',
    texto: '#1E1B4B',
    textoSuave: '#6B7280',
    textoRodape: '#9CA3AF',
    destaque: '#8B5CF6',
    destaqueSuave: '#EDE9FE',
    cardFundo: '#FFFFFF',
    cardBorda: '#DDD6FE',
    cardBordaSelecionada: '#8B5CF6'
  },
  {
    id: 'laranja-energia',
    nome: 'Laranja Energia',
    preview: ['#FFFBEB', '#F97316', '#FED7AA'],
    fundo: '#FFFBEB',
    fundoSecundario: '#FEF3C7',
    texto: '#7C2D12',
    textoSuave: '#92400E',
    textoRodape: '#A16207',
    destaque: '#F97316',
    destaqueSuave: '#FED7AA',
    cardFundo: '#FFFFFF',
    cardBorda: '#FED7AA',
    cardBordaSelecionada: '#F97316'
  },
  {
    id: 'vermelho-urgencia',
    nome: 'Vermelho Urgência',
    preview: ['#FFFFFF', '#DC2626', '#FEE2E2'],
    fundo: '#FFFFFF',
    fundoSecundario: '#FEF2F2',
    texto: '#7F1D1D',
    textoSuave: '#6B7280',
    textoRodape: '#9CA3AF',
    destaque: '#DC2626',
    destaqueSuave: '#FEE2E2',
    cardFundo: '#FFFFFF',
    cardBorda: '#FECACA',
    cardBordaSelecionada: '#DC2626'
  },
  {
    id: 'amarelo-otimista',
    nome: 'Amarelo Otimista',
    preview: ['#FEFCE8', '#EAB308', '#FEF08A'],
    fundo: '#FEFCE8',
    fundoSecundario: '#FEF9C3',
    texto: '#713F12',
    textoSuave: '#854D0E',
    textoRodape: '#A16207',
    destaque: '#EAB308',
    destaqueSuave: '#FEF08A',
    cardFundo: '#FFFFFF',
    cardBorda: '#FEF08A',
    cardBordaSelecionada: '#EAB308'
  },
  {
    id: 'verde-agua',
    nome: 'Verde Água',
    preview: ['#F0FDFA', '#14B8A6', '#CCFBF1'],
    fundo: '#F0FDFA',
    fundoSecundario: '#CCFBF1',
    texto: '#134E4A',
    textoSuave: '#0F766E',
    textoRodape: '#115E59',
    destaque: '#14B8A6',
    destaqueSuave: '#CCFBF1',
    cardFundo: '#FFFFFF',
    cardBorda: '#99F6E4',
    cardBordaSelecionada: '#14B8A6'
  },
  {
    id: 'grafite-minimal',
    nome: 'Grafite Minimal',
    preview: ['#F5F5F5', '#404040', '#D4D4D4'],
    fundo: '#F5F5F5',
    fundoSecundario: '#E5E5E5',
    texto: '#171717',
    textoSuave: '#525252',
    textoRodape: '#737373',
    destaque: '#404040',
    destaqueSuave: '#D4D4D4',
    cardFundo: '#FFFFFF',
    cardBorda: '#D4D4D4',
    cardBordaSelecionada: '#404040'
  },
  {
    id: 'escuro-elegante',
    nome: 'Escuro Elegante',
    preview: ['#0A0A0A', '#FAFAFA', '#404040'],
    fundo: '#0A0A0A',
    fundoSecundario: '#171717',
    texto: '#FAFAFA',
    textoSuave: '#A3A3A3',
    textoRodape: '#525252',
    destaque: '#FAFAFA',
    destaqueSuave: '#262626',
    cardFundo: '#171717',
    cardBorda: '#262626',
    cardBordaSelecionada: '#FAFAFA',
    modoEscuro: true
  },
  {
    id: 'oceano-profundo',
    nome: 'Oceano Profundo',
    preview: ['#0C1E3C', '#38BDF8', '#1E3A8A'],
    fundo: '#0C1E3C',
    fundoSecundario: '#1E3A8A',
    texto: '#F0F9FF',
    textoSuave: '#93C5FD',
    textoRodape: '#60A5FA',
    destaque: '#38BDF8',
    destaqueSuave: '#1E3A8A',
    cardFundo: '#1E3A8A',
    cardBorda: '#1E40AF',
    cardBordaSelecionada: '#38BDF8',
    modoEscuro: true
  }
];

export const coresCTA = [
  { id: 'auto',    nome: 'Automático (usa o destaque)', cor: null },
  { id: 'preto',   nome: 'Preto',    cor: '#111827' },
  { id: 'azul',    nome: 'Azul',     cor: '#0EA5E9' },
  { id: 'verde',   nome: 'Verde',    cor: '#10B981' },
  { id: 'rosa',    nome: 'Rosa',     cor: '#EC4899' },
  { id: 'roxo',    nome: 'Roxo',     cor: '#8B5CF6' },
  { id: 'laranja', nome: 'Laranja',  cor: '#F97316' },
  { id: 'vermelho',nome: 'Vermelho', cor: '#DC2626' },
  { id: 'amarelo', nome: 'Amarelo',  cor: '#EAB308' }
];

export function getPaleta(id) {
  return paletas.find(p => p.id === id) || paletas[0];
}